// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ForceStep
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidForceStepPackageString = "3d735e2d-9fd5-4f6f-91b3-eb8f318b05e1";
        public static Guid guidForceStepPackage = new Guid(guidForceStepPackageString);

        public const string guidForceStepPackageCmdSetString = "22f33e59-0867-4f98-ae3c-b2ca2fe0222a";
        public static Guid guidForceStepPackageCmdSet = new Guid(guidForceStepPackageCmdSetString);

        public const string guidImagesString = "18a739b1-142f-4228-87e1-fc19e0f4dc73";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ForceStepOutId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}