// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ForceStep
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidForceStepPackageString = "3d735e2d-9fd5-4f6f-91b3-eb8f318b05e1";
        public static Guid guidForceStepPackage = new Guid(guidForceStepPackageString);

        public const string guidForceStepPackageCmdSetString = "466498cc-0795-4718-bcb7-98dc3982eb39";
        public static Guid guidForceStepPackageCmdSet = new Guid(guidForceStepPackageCmdSetString);

        public const string guidImagesString = "c62a1fac-65b1-407e-8309-7b73bb72e06c";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ForceContinueId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}