// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ForceStep
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidForceStepPackageString = "0f041c2e-ad3e-4cb4-888b-e5a46e5b2d0e";
        public static Guid guidForceStepPackage = new Guid(guidForceStepPackageString);

        public const string guidForceStepPackageCmdSetString = "c210ff9e-e207-43f5-935e-5ed58eb9210d";
        public static Guid guidForceStepPackageCmdSet = new Guid(guidForceStepPackageCmdSetString);

        public const string guidImagesString = "77c241c3-73da-4d53-aef0-3fe548d09a6e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ForceStepId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}