// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ForceStep
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidForceStepPackageString = "d8a1c04d-42ae-4bb7-b053-aae99c2720a4";
        public static Guid guidForceStepPackage = new Guid(guidForceStepPackageString);

        public const string guidForceStepPackageCmdSetString = "5499ab04-087c-4366-bd73-ff583b883993";
        public static Guid guidForceStepPackageCmdSet = new Guid(guidForceStepPackageCmdSetString);

        public const string guidImagesString = "6ac84bf9-c454-4e6d-b142-686e733cd0e9";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "890df36a-4519-40e5-a2fe-239a622ef73d";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "8c2ae99c-7371-4407-b7b6-5ec4e2f6ac42";
        public static Guid guidImages2 = new Guid(guidImages2String);

        public const string guidImages3String = "bd82b7a0-b949-45e6-968d-48b3148c266c";
        public static Guid guidImages3 = new Guid(guidImages3String);

        public const string guidImages4String = "6d07e6cb-f1b0-4ac5-8795-f7d3a1809214";
        public static Guid guidImages4 = new Guid(guidImages4String);

        public const string guidImages5String = "2223fe99-d7b8-4426-8082-47423371186f";
        public static Guid guidImages5 = new Guid(guidImages5String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ForceStepCommandId = 0x0100;
        public const int cmdidForceContinue = 0x1021;
        public const int cmdidForceStepOut = 0x1022;
        public const int cmdidForceStepInto = 0x1023;
        public const int cmdidManuallyDisable = 0x1024;
        public const int cmdidManuallyEnable = 0x1025;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0001;
        public const int bmpPic3 = 0x0001;
        public const int bmpPic4 = 0x0001;
        public const int bmpPic5 = 0x0001;
        public const int bmpPic6 = 0x0001;
    }
}