// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ForceStep
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidForceStepPackageString = "d8a1c04d-42ae-4bb7-b053-aae99c2720a4";
        public static Guid guidForceStepPackage = new Guid(guidForceStepPackageString);

        public const string guidForceStepPackageCmdSetString = "5499ab04-087c-4366-bd73-ff583b883993";
        public static Guid guidForceStepPackageCmdSet = new Guid(guidForceStepPackageCmdSetString);

        public const string guidImagesString = "6ac84bf9-c454-4e6d-b142-686e733cd0e9";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ForceStepCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}